name: 'dbt_example'
version: '1.0.0'

profile: 'dbt_example'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

models:
  dbt_example:
    staging:
      schema: staging
      materialized: table

    intermediate: 
      materialized: ephemeral

    marts: 
      schema: marts
      materialized: table
      tags: ['marts']